"""Initial migration

Revision ID: 8eb85d4e488b
Revises: 
Create Date: 2026-07-07 03:27:46.937023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb85d4e488b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_experiences_expert_id'), 'experiences', ['expert_id'], unique=False)
    op.create_index(op.f('ix_experiences_id'), 'experiences', ['id'], unique=False)
    op.drop_constraint(op.f('experiences_expert_id_fkey'), 'experiences', type_='foreignkey')
    op.create_foreign_key(None, 'experiences', 'experts', ['expert_id'], ['id'], ondelete='CASCADE')
    op.add_column('experts', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('experts', sa.Column('location', sa.String(length=255), nullable=True))
    op.alter_column('experts', 'bio',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('experts', 'hourly_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('ix_experts_user_id'), table_name='experts')
    op.drop_constraint(op.f('experts_user_id_fkey'), 'experts', type_='foreignkey')
    op.drop_column('experts', 'rating')
    op.drop_column('experts', 'completed_projects')
    op.drop_column('experts', 'user_id')
    op.drop_column('experts', 'experience_years')
    op.create_index(op.f('ix_portfolios_expert_id'), 'portfolios', ['expert_id'], unique=False)
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.drop_constraint(op.f('portfolios_expert_id_fkey'), 'portfolios', type_='foreignkey')
    op.create_foreign_key(None, 'portfolios', 'experts', ['expert_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_skills_expert_id'), 'skills', ['expert_id'], unique=False)
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.drop_constraint(op.f('skills_expert_id_fkey'), 'skills', type_='foreignkey')
    op.create_foreign_key(None, 'skills', 'experts', ['expert_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.create_foreign_key(op.f('skills_expert_id_fkey'), 'skills', 'experts', ['expert_id'], ['id'])
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_expert_id'), table_name='skills')
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.create_foreign_key(op.f('portfolios_expert_id_fkey'), 'portfolios', 'experts', ['expert_id'], ['id'])
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_expert_id'), table_name='portfolios')
    op.add_column('experts', sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('experts', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('experts', sa.Column('completed_projects', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('experts', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('experts_user_id_fkey'), 'experts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_experts_user_id'), 'experts', ['user_id'], unique=False)
    op.alter_column('experts', 'hourly_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('experts', 'bio',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('experts', 'location')
    op.drop_column('experts', 'full_name')
    op.drop_constraint(None, 'experiences', type_='foreignkey')
    op.create_foreign_key(op.f('experiences_expert_id_fkey'), 'experiences', 'experts', ['expert_id'], ['id'])
    op.drop_index(op.f('ix_experiences_id'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_expert_id'), table_name='experiences')
    # ### end Alembic commands ###
